### ISSUE TITLE
AudioSystem cant play multiple audios at the same time

### ISSUE THREAD

**Issue by nougatchi** [ryelow90210/dreary#3]
**This is just for me.**

AudioSystem needs the ability to play multiple audios. It can only play 1 or else an error occurs and it wont play the other audio.
Currently uses wasapi. Perhaps change that?

**Comment by typicalname0** [comment]
tell me when you release thsi i want to play it

**Comment by nougatchi** [comment]
Forgot to say, commit [9f8ce7aed6362bfe25586de84d80717742267d5a](https://github.com/ryelow90210/dreary/commit/9f8ce7aed6362bfe25586de84d80717742267d5a) begins a switch to XAudio2

**Comment by nougatchi** [comment]
Perhaps cancelling using CSCore. Github Actions doesnt like it

**Comment by nougatchi** [comment]
Using MediaPlayer until further notice.
